services:
  # --- INFRAESTRUTURA ---
  db-usuarios:
    image: postgres:17
    container_name: usuarios
    environment:
      POSTGRES_USER: api-financeira
      POSTGRES_PASSWORD: dev1234
      POSTGRES_DB: usuarios_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_usuarios:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U api-financeira -d usuarios_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  db-transacoes:
    image: postgres:17
    container_name: transacoes
    environment:
      POSTGRES_USER: api-financeira
      POSTGRES_PASSWORD: dev1234
      POSTGRES_DB: transacoes_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_transacoes:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U api-financeira -d transacoes_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-dev
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    restart: unless-stopped

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://:29092,PLAINTEXT_HOST://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "9090:8080"
    restart: always
    environment:
      KAFKA_CLUSTERS_0_NAME: Local Kafka Cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
    depends_on:
      - kafka

  # --- MICROSSERVIÇOS (ORDEM DE INICIALIZAÇÃO) ---

  user-service:
    build: ./user-service
    container_name: ms1-user-service
    ports:
      - "${MS1_APP_PORT}:${MS1_APP_PORT}"
    env_file: .env
    depends_on:
      db-usuarios:
        condition: service_healthy
      kafka:
        condition: service_started

  producer-transaction-service:
    build: ./producer-transaction-service
    container_name: ms2-producer-service
    ports:
      - "${MS2_APP_PORT}:${MS2_APP_PORT}"
    env_file: .env
    depends_on:
      user-service:
        condition: service_started
      db-transacoes:
        condition: service_healthy

  consumer-transaction-service:
    build: ./consumer-transaction-service
    container_name: ms3-consumer-service
    ports:
      - "${MS3_APP_PORT}:${MS3_APP_PORT}"
    env_file: .env
    depends_on:
      producer-transaction-service:
        condition: service_started
      db-transacoes:
        condition: service_healthy

volumes:
  postgres_data_usuarios:
  postgres_data_transacoes: