services:
  postgres:
    image: postgres:17
    container_name: usuarios
    environment:
      POSTGRES_USER: api-financeira
      POSTGRES_PASSWORD: dev1234
      POSTGRES_DB: usuarios_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_usuarios:/var/lib/postgresql/data
    restart: unless-stopped

  postgres2:
    image: postgres:17
    container_name: transacoes
    environment:
      POSTGRES_USER: api-financeira
      POSTGRES_PASSWORD: dev1234
      POSTGRES_DB: transacoes_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_transacoes:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-dev
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    restart: unless-stopped

volumes:
  postgres_data_usuarios:
  postgres_data_transacoes:
